### ISSUE TITLE
Missing "=" character in the request line for requirements.txt

### ISSUE THREAD

**Issue by tjnull** [Ziconius/FudgeC2#3]
**Describe the bug**
During Installation of Fudge C2 the requirements.txt file compiled an error that an "=" sign was missing for the following package:

requests=2.21.0

**To Reproduce**
Edit the requirements.txt file to include another "=" character:

requests==2.21.0

**Screenshots**
![image](https://user-images.githubusercontent.com/34779398/73714203-312df180-46de-11ea-8dd0-13d5f7f5ad42.png)

**Desktop (please complete the following information):**
 - OS: Kali Linux 2020.1

Latest Version of Fudge C2 today. 

**Additional context**

Looking to get FudgeC2 packaged into Kali Linux full time if possible :D

**Comment by Ziconius** [comment]
Updated the requirements.txt file. A second issue was also found and fixed in an import reference in the download_file.py

Fixed in commit: afe36a7e95db3d631505b63af617c733a078b2dd

Thanks for report & kind words.
