### ISSUE TITLE
Error: No valid network profiles submitted.

### ISSUE THREAD

**Issue by jorgeorchilles** [Ziconius/FudgeC2#4]
**Describe the bug**
Created a new campaign (test) and then went to create Implant but get error: 
Error: No valid network profiles submitted.

I fill out the required fields:
Implant title: HTTP
Implant domain/IP: 10.0.0.112 (IP of my C2 server)
Implant description: HTTPTest
Basic HTTP Profile: Check
TCP Port for Binary Listener: 80
Everything else is default.

I tried with a Listener running and stopped:
Configured listeners:
Name: HTTP
Network Profile: BasicHttpProfile
Port: 80
State: Stopped

**To Reproduce**
Fresh install on 2/11/2020

Created Listener:
127.0.0.1 - - [11/Feb/2020 14:51:33] "GET /listener HTTP/1.1" 200 -
 * Serving Flask app "939de6b9-5342-4e6f-87fe-d440a81ab8f0" (lazy loading)
127.0.0.1 - - [11/Feb/2020 14:53:09] "POST /api/v1/listener/change HTTP/1.1" 302 -
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
127.0.0.1 - - [11/Feb/2020 14:53:09] "GET /listener HTTP/1.1" 200 -

Try to create an Implant on "test" campaign with following options:
Implant title: HTTP
Implant domain/IP: 10.0.0.112 (IP of my C2 server)
Implant description: HTTPTest
Basic HTTP Profile: Check
TCP Port for Binary Listener: 80
Everything else is default.

Get this error in GUI:
Error: No valid network profiles submitted.

This error in console:
127.0.0.1 - - [11/Feb/2020 14:54:01] "GET /1/implant/create HTTP/1.1" 200 -
Returning obf_a: 0 to ofb_b: 0
Error: No valid network profiles submitted.
127.0.0.1 - - [11/Feb/2020 14:54:14] "POST /1/implant/create HTTP/1.1" 409 -

**Expected behavior**
Implant created.

**Screenshots**
![image](https://user-images.githubusercontent.com/52384511/74249049-907b9b00-4cb6-11ea-9df9-121f16f4e8ff.png)

**Desktop (please complete the following information):**
 - OS: Linux slingshot 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Browser Firefox

**Additional context**
 - Implant configuration
 - Listener configuration
 - Powershell version on target (if known)

**Comment by Ziconius** [comment]
Thanks for the issue submission - I'm pretty sure I know where this has spawned from. 

Prior to the network profile implementation (0.5.2) the checkbox was a requirement. If you submit the same form leaving the checkboxes unchecked, anything left blank is ignored and anything with an integer is submitted. 

I'm reworking this now to clean up the UI and remove this bug now! I should have this pushed out within the next few hours. I'll update here once it's live.

**Comment by jorgeorchilles** [comment]
Same issue when I don't check either of the two boxes and leave the two text fields empty.

**Comment by Ziconius** [comment]
To clarify, you need to submit at least one network profile (or the implant won't know where to connect back to).

I've pushed some changes up to the development branch on commit cf79923f89767031ad5fc889f3005568578480f7 these should remove the UI issues and the smooth our the implant template creation.

I'll verify everything is working this evening then merge the commit providing no other issues are found.

Thanks again! :)

**Comment by jorgeorchilles** [comment]
Thanks, I will wait for the update. I have a listeners running:
[image: image.png]

Best Regards,
Jorge Orchilles
LinkedIn <https://www.linkedin.com/in/jorgeorchilles/>
Follow me on Twitter <https://twitter.com/jorgeorchilles>

**Comment by Ziconius** [comment]
The changes to UI and improved error messages have now been merged into master via commit cf79923f89767031ad5fc889f3005568578480f7

Thanks!
